---
title: "**Contribución de las Remesas al Consumo y su Impacto en el Crecimiento Económico del Ecuador entre 2010 y 2022**"
author: "**Autor:** Del Rosario, Alan; adelr3@unemi.edu.ec\\

  **Co-autor(es):** Bravo, Kerly;\\
  
  **Orientador/a:**\\
  "
format: 
  pdf: 
    documentclass: article
    pdf-engine: xelatex
    number-sections: true
    header-includes:
      - \usepackage{amsmath}
      - \usepackage{fontspec}
      - \setmainfont{Arial}
      - \setsansfont{Arial}
      - \setmathfont{XITS Math}
      - \usepackage[spanish]{babel}
      - \usepackage{csquotes}
      - \usepackage{setspace}
      - \setlength{\parindent}{0.5in}  # Sangría de 0.5 pulgadas
      - \usepackage[letterpaper,margin=1in, centering]{geometry}
fontsize: 11pt
---

\begin{center}
  Universidad Estatal de Milagro/ Facultad de Ciencias Sociales, Educación Comercial Y Derecho-FACSECYD
\end{center}

\begin{abstract}
Este estudio analiza la contribución de las remesas al consumo de los hogares y su impacto en el crecimiento económico de Ecuador durante el periodo 2015-2022. Se utiliza un enfoque econométrico basado en dos modelos de regresión lineal simple para comprender la relación indirecta entre las remesas y el Producto Interno Bruto (PIB). En la primera etapa, se evalúa el efecto de las remesas sobre el consumo de los hogares, determinando el grado en que el ingreso adicional proveniente de remesas influye en el gasto de los hogares. En la segunda etapa, se estudia cómo el consumo resultante de las remesas afecta el PIB de Ecuador, demostrando que el crecimiento económico se ve influido por las variaciones en el consumo privado. Los resultados sugieren que las remesas tienen un impacto positivo significativo en el consumo, que a su vez impulsa el crecimiento del PIB. 
\end{abstract}

**Palabras clave:** Crecimiento económico, remesas, consumo

# Introducción

Las remesas han sido un componente fundamental en la economía de numerosos países en desarrollo, y Ecuador no es la excepción. Este flujo de capital proveniente del extranjero representa una fuente de ingresos importante para muchos hogares, especialmente aquellos cuyos miembros han migrado buscando mejores oportunidades económicas. Las remesas no solo contribuyen a la mejora de la calidad de vida de las familias receptoras, sino que también tienen el potencial de impactar significativamente en el consumo nacional, lo que a su vez puede influir en el crecimiento económico del país.

En el caso de Ecuador, el flujo de remesas ha jugado un rol determinante en el consumo privado, actuando como un mecanismo de soporte para la demanda interna, especialmente en tiempos de desaceleración económica o inestabilidad financiera. Durante el período 2015-2022, el país enfrentó desafíos económicos que incluyeron la caída de los precios del petróleo, desastres naturales como el terremoto de 2016 y, más recientemente, la crisis sanitaria y económica derivada de la pandemia de COVID-19. En este contexto, las remesas han sido un factor de alivio para los hogares ecuatorianos, proporcionando una inyección de recursos que favorece el consumo.

Este estudio profundiza en la contribución de las remesas al consumo de los hogares y su posterior efecto en el crecimiento económico de Ecuador. A través de un análisis econométrico, se pretende identificar la relación entre el ingreso adicional por remesas y el gasto de los hogares, así como evaluar cómo este gasto influye en el Producto Interno Bruto (PIB).

# Objetivos

## Objetivo general

Analizar la contribución de las remesas al consumo de los hogares y su impacto en el crecimiento económico de Ecuador durante el periodo 2015-2022.

## Objetivos específicos

- Evaluar el efecto de las remesas sobre el consumo de los hogares en Ecuador, identificando la magnitud del impacto que el ingreso adicional proveniente de remesas tiene sobre el gasto de las familias receptoras.
- Determinar la relación entre el consumo derivado de las remesas y el crecimiento económico, analizando cómo las variaciones en el consumo privado influencian el Producto Interno Bruto (PIB) del país.
- Identificar las tendencias y variaciones en la recepción de remesas durante el periodo de estudio, considerando los factores externos e internos que han influido en estos flujos de capital.

# Metodología

## Enfoque econométrico

El estudio emplea un modelo en dos etapas o **regresión escalonada**, con el fin de analizar el impacto de las remesas en el consumo de manera individual y, posteriormente, evaluar cómo esta relación influye en el Producto Interno Bruto (PIB).

### Primera etapa: Relación entre consumo y remesas

En esta fase, se emplea un modelo de regresión lineal simple para medir cómo las remesas afectan el consumo de los hogares. El modelo econométrico se describe como:

$$
CONSUMO = \alpha_0 + \alpha_1 (\text{Remesas}) + \varepsilon_1
$$

Donde:

- **Y**: Consumo de los hogares  

- **X**: Cantidad de remesas recibidas  

- **$\alpha_0$**: Intercepto  

- **$\alpha_1$**: Coeficiente de las remesas   

- **$\varepsilon_1$**: Término de error 

### Segunda etapa: Relación entre consumo ajustado por remesas y PIB

En esta etapa, se construye una variable denominada **$CONSUMO_R$** (Concumo percibidos por remesas), que almacena los valores ajustados obtenidos de la primera regresión. Luego, se utiliza un segundo modelo para medir cómo el consumo impulsado por las remesas impacta el PIB:

$$
PIB = \beta_0 + \beta_1 (CONSUMO_R)+\beta_2 (GASTO_p)+\beta_3 (INV)+\beta_4 (EXP_n) + \varepsilon_2
$$

Donde:

- **$PIB$**: Producto Interno Bruto

- **$CONSUMO_R$**: Consumo impulsado por remesas

- **$GASTO_p$**: Gasto público 

- **$INV$**: Inversión 

- **$EXP_n$**: Exportaciones netas

- **$\beta_0$**: Intercepto

- **$\beta_1$**: Coeficiente del consumo ajustado

- **$\beta_2$**: Coeficiente del gasto público

- **$\beta_3$**: Coeficiente de la inversión

- **$\beta_4$**: Coeficiente de las exportaciones netas

- **$\varepsilon_2$**: Término de error

## Materiales estadísticos

- Bases de datos de remesas y consumo de hogares en Ecuador (2015-2022)
- Registros del PIB publicados por el Banco Central del Ecuador
- Software estadístico para análisis econométrico (como R o Stata)

# Resultados y discusión

```{r echo=FALSE}
# Cargar librerías necesarias
library(knitr)
library(kableExtra)
# Definir los datos de la tabla
data <- data.frame(
  Variable = c("Remesas", "Consumo Ajustado", "GASTO_PUBLICO", "INVERSION", "EXPORTA_NETAS", "Constante"),
  `Consumo Ajustado` = c("5.240***", "", "", "", "", "47,713,158.000***"),
  `Error Consumo Ajustado` = c("(1.676)", "", "", "", "", "(5,191,758.000)"),
  PIB = c("", "0.855***", "4.092***", "0.161", "-0.977", "-18,017,905.000"),
  `Error PIB` = c("", "(0.179)", "(0.346)", "(0.144)", "(0.581)", "(11,485,484.000)")
)
# Crear la tabla con kable y aplicar formato
kbl(data, align = "c", col.names = c("Variable", "Consumo Ajustado", "(Error Estándar)", "PIB", "(Error Estándar)")) %>%
  kable_classic(full_width = F) %>%
  add_header_above(c(" " = 1, "Dependent variable" = 4)) %>%
  add_header_above(c("Resultado de las regresiones de dos etapas" = 5)) %>%
  add_footnote(c("Observaciones: 13", 
                 "R²: 0.471 (Consumo Ajustado), 0.968 (PIB)", 
                 "R² Ajustado: 0.422 (Consumo Ajustado), 0.952 (PIB)", 
                 "Error Estándar Residual: 4,364,795.000 (df = 11), 2,175,130.000 (df = 8)", 
                 "Estadístico F: 9.779*** (df = 1; 11), 60.151*** (df = 4; 8)",
                 "Nota: *p<0.1; **p<0.05; ***p<0.01"))
```

*(Nota: Los resultados y la discusión serán incorporados una vez finalizados los cálculos econométricos.  En este ambito se registará el impacto y discutir posibles variaciones en función de los factores económicos externos mencionados).*


# Discusión
## Interpretación de coeficientes:


## Intervalos de confianza

## Pruebas de heterocedasticidad y autocorrelación

# Conclusiones

*(Nota: Las conclusiones estarán disponibles al cierre del análisis de resultados).*

# Referencias Bibliográficas
